server:
  port: 8001
  
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml     #mybatis配置文件所在路徑
  type-aliases-package: com.springCloudDemo.entities   #所有Entity別名類所在package
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                    #mapper映射文件
  
spring:
  application:
    name: microservicecloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource         #當前資料源操作類型
    driver-class-name: org.gjt.mm.mysql.Driver           #mysql驅動包
    url: jdbc:mysql://localhost:3306/todolist?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Taipei #資料庫名稱，請自訂
    username: root #資料庫帳號，請自訂
    password:  #資料庫密碼，請自訂
    dbcp2:
      min-idle: 5                                        #資料庫連接池的最小維持連接數
      initial-size: 5                                    #初始化連接數
      max-idle: 5                                        #最大連接數
      max-wait-millis: 200                               #等待連接獲取最大超時時間